# Generated by Django 3.2 on 2023-02-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230217_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='comment',
        ),
    ]
