# Generated by Django 3.2 on 2023-02-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_review_text_review_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customer',
            new_name='created_by',
        ),
    ]
