# Generated by Django 3.2 on 2023-02-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_customer_review_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_review',
        ),
    ]
